EVALUATE
	SELECTCOLUMNS(
		TOPN(
			1000,
			'Participants',
			'Participants'[EXIT DATE],
			ASC
		),
		'Participants'[EXIT DATE],
		'Participants'[LWDB],
		'Participants'[RESPONSIBLE OFFICE],
		'Participants'[PARTICIPATION DATE],
		'Participants'[GRANT ENROLL DATE],
		'Participants'[LAST GRANT ACTIVITY DATE],
		'Participants'[PROJECTED GRANT ACTIVITY END DATE],
		'Participants'[RECEIVED CREDENTIAL],
		'Participants'[ENTERED EMPLOYMENT],
		'Participants'[WITH DISABILITY],
		'Participants'[APP ID]
	)
	ORDER BY 'Participants'[GRANT ENROLL DATE] DESC