/// Reference table of Local Workforce Development Board (LWDB) region names. Contains one row per region and serves as the primary slicer table for filtering all enrollment, services, and exit measures by geography.
table Regions
	lineageTag: 165f9ac7-3eab-4f76-9e00-94453aace98b

	/// The unique name of a Local Workforce Development Board (LWDB) region. This is the primary key of the Regions table and the field used in the region slicer.
	column 'REGION LWDB'
		dataType: string
		isHidden
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 78056885-691e-4f63-ab14-af7603536c87
		summarizeBy: none
		sourceColumn: REGION LWDB

		annotation SummarizationSetBy = Automatic

	/// Column REGION CODE from the Regions table. Used for filtering, grouping, relationships, or calculation logic in the DOR AJCC Collaboration semantic model.
	column 'REGION CODE'
		dataType: int64
		isHidden
		formatString: #,0
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 32cf3d5e-f01f-44cd-b407-5556a78dfd8a
		summarizeBy: none
		sourceColumn: REGION CODE

		annotation SummarizationSetBy = Automatic

	/// Column REGION SHORT ABBR from the Regions table. Used for filtering, grouping, relationships, or calculation logic in the DOR AJCC Collaboration semantic model.
	column 'REGION SHORT ABBR'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: e095d299-1c0e-4237-afb9-c8398ea4f35f
		summarizeBy: none
		sourceColumn: REGION SHORT ABBR

		annotation SummarizationSetBy = Automatic

	partition Regions = m
		mode: import
		queryGroup: dimRegions
		source = ```
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\StevenFoster\Downloads\Grant Enrollment Sample Data.xlsx"), true, true),
				  PromoteHeaders = Source{[Item = "Regions", Kind = "Sheet"]}[Data]
				, 
				  TypePairs = {
				    {"REGION CODE", Int64.Type}, 
				    {"REGION LWDB", type text},
				    {"REGION SHORT ABBR", type text}
				  }, 
				  ExistingCols = Table.ColumnNames(
				    PromoteHeaders
				  ), 
				  // Keep type rules only for columns that actually exist
				  TypePairsExistingOnly = List.Select(
				    TypePairs, 
				    each List.Contains(
				      ExistingCols, 
				      _{0}
				    )
				  ), 
				  // Convert those explicit pairs into a lookup record: ColumnName -> Type
				  ExplicitTypeMap = Record.FromList(
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{1}
				    ), 
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{0}
				    )
				  ), 
				  // - If we specified a type in ExplicitTypeMap, use it.
				  // - Otherwise default to type text.
				  AllTypePairs = List.Transform(
				    ExistingCols, 
				    (c) => {
				      c, 
				      Record.FieldOrDefault(
				        ExplicitTypeMap, 
				        c, 
				        type text
				      )
				    }
				  ), 
				  // Apply types in one go
				  ChangeTypes
				    = Table.TransformColumnTypes(
				    PromoteHeaders, 
				    AllTypePairs
				  )
				in
				  ChangeTypes
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

