/// Aggregated data sourced from (All) DOR-AJCC Collab_ServicesProvided file. Records every service event including the type of service, the provider, start and end dates, completion status, and associated program and region. Used to count and categorize services delivered across regions and time periods.
table ServicesProvided
	lineageTag: 59de6b89-760b-43fa-9028-f9cd2339ed4c

	/// The DOR office location that delivered or is responsible for this service record.
	column OFFICE
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: fc7182e0-fc10-4430-9a8e-f2937ac228cb
		summarizeBy: none
		sourceColumn: OFFICE

		annotation SummarizationSetBy = Automatic

	/// The name of the specific service that was provided to the participant.
	column SERVICE
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 8d7cdbc7-b1d2-43ca-85a8-8735e83e9a30
		summarizeBy: none
		sourceColumn: SERVICE

		annotation SummarizationSetBy = Automatic

	/// Indicates whether the service has been completed, is in progress, or was cancelled.
	column 'COMPLETION STATUS'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 198f73b4-4c29-43c6-a416-2eff2b5ab2ae
		summarizeBy: none
		sourceColumn: COMPLETION STATUS

		annotation SummarizationSetBy = Automatic

	/// The workforce program (e.g. WIOA, DOR) under which this service was delivered.
	column PROGRAM
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 05716576-0c0d-43e3-b9bf-7b62a2c9a093
		summarizeBy: none
		sourceColumn: PROGRAM

		annotation SummarizationSetBy = Automatic

	/// The organization or vendor that delivered the service to the participant.
	column PROVIDER
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 3b01b126-0f51-4ad0-938d-368901d66b21
		summarizeBy: none
		sourceColumn: PROVIDER

		annotation SummarizationSetBy = Automatic

	/// The date and time this service record was created in the system.
	column 'CREATE DATE'
		dataType: dateTime
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 3681b3a2-2727-4106-b503-658542fc6204
		summarizeBy: none
		sourceColumn: CREATE DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The actual date on which the participant began receiving this service.
	column 'ACTUAL BEGIN DATE'
		dataType: dateTime
		isHidden
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 086cff69-7c40-42c0-9008-791b64e43f86
		summarizeBy: none
		sourceColumn: ACTUAL BEGIN DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The originally planned start date for this service before it was delivered.
	column 'PROJECTED BEGIN DATE'
		dataType: dateTime
		isHidden
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: c1ac8a67-fab1-4412-8aa5-d7da14eb88eb
		summarizeBy: none
		sourceColumn: PROJECTED BEGIN DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The actual date on which the service concluded for this participant.
	column 'ACTUAL END DATE'
		dataType: dateTime
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 21f9f498-7a4f-4242-b500-2f6fbad6ea2a
		summarizeBy: none
		sourceColumn: ACTUAL END DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The originally planned end date for this service.
	column 'PROJECTED END DATE'
		dataType: dateTime
		isHidden
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 2af9d42e-5ff7-482e-b69b-80d75eda5df3
		summarizeBy: none
		sourceColumn: PROJECTED END DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Indicates whether this service is part of a registered apprenticeship program (Y/N).
	column 'REGISTERED APPRENTICESHIP'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 269641fc-c16d-4d0d-ab9f-8db6bad974a5
		summarizeBy: none
		sourceColumn: REGISTERED APPRENTICESHIP

		annotation SummarizationSetBy = Automatic

	/// Self-reported indicator of whether the participant identifies as Hispanic or Latino.
	column HISPANIC
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: f714e62c-5f31-4b91-a575-8151cb45f59f
		summarizeBy: none
		sourceColumn: HISPANIC

		annotation SummarizationSetBy = Automatic

	/// Free-text notes entered by staff about this specific service record.
	column COMMENTS
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: aa57ebc3-8b7c-45ea-8bed-d9b8e32292fd
		summarizeBy: none
		sourceColumn: COMMENTS

		annotation SummarizationSetBy = Automatic

	/// The system username of the case manager or staff member who recorded this service.
	column 'USER ID'
		dataType: int64
		formatString: #,0
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 51eca277-a266-4fe6-a99f-7b1234bc346a
		summarizeBy: none
		sourceColumn: USER ID

		annotation SummarizationSetBy = Automatic

	/// The DOR office that holds primary responsibility for the participant at the time of service.
	column 'OFFICE OF RESPONSIBILITY'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: d2861723-4f95-4cd6-8439-03ed2af963b6
		summarizeBy: none
		sourceColumn: OFFICE OF RESPONSIBILITY

		annotation SummarizationSetBy = Automatic

	/// The North American Industry Classification System code for the industry related to this service or employer.
	column NAICS
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 8c632d0d-de7c-4ccf-8d6f-1d0d020a8b2c
		summarizeBy: none
		sourceColumn: NAICS

		annotation SummarizationSetBy = Automatic

	/// The O*NET occupation code associated with the service or participant's employment goal.
	column ONET
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: e42c5665-ebb2-484d-9797-60dff931a92e
		summarizeBy: none
		sourceColumn: ONET

		annotation SummarizationSetBy = Automatic

	/// Specifies the type of registered apprenticeship (e.g. time-based, competency-based) if applicable.
	column 'TYPE OF APPRENTICESHIP'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 4452a31b-3187-46c3-9482-8e0924fe012a
		summarizeBy: none
		sourceColumn: TYPE OF APPRENTICESHIP

		annotation SummarizationSetBy = Automatic

	/// The Local Workforce Development Board region associated with this service record.
	column 'REGION LWDB'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 30fd27fb-6e55-4a3d-9bed-d079ecfd6fb6
		summarizeBy: none
		sourceColumn: REGION LWDB

		annotation SummarizationSetBy = Automatic

	/// The most recent date on which the participant was recorded as employed, relevant to employment outcome tracking.
	column 'MOST RECENT EMPLOYMENT DATE'
		dataType: dateTime
		formatString: m/d/yyyy
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 7dbd8852-d3bc-4042-b5bf-93c6a75ce3e8
		summarizeBy: none
		sourceColumn: MOST RECENT EMPLOYMENT DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// The mode of service delivery, such as in-person, virtual, or hybrid.
	column 'LEARNING MODE'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 8187335a-1dde-44b1-9816-0605b95afd6e
		summarizeBy: none
		sourceColumn: LEARNING MODE

		annotation SummarizationSetBy = Automatic

	/// A code identifying the agency responsible for the participant's case.
	column 'AGENCY CODE'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: c4c6e22e-9b2e-43e3-896b-f3fd1cfbf31d
		summarizeBy: none
		sourceColumn: AGENCY CODE

		annotation SummarizationSetBy = Automatic

	/// Indicates whether the participant has a prior felony or criminal record (Y/N).
	column 'EX OFFENDER'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 969962d9-edff-405e-97e5-af946036f6ef
		summarizeBy: none
		sourceColumn: EX OFFENDER

		annotation SummarizationSetBy = Automatic

	/// A short prefix code that groups services into high-level categories (e.g. 108 = Co-Enrollment, 140 = Referral). Used to filter specific service types in measures.
	column 'SERVICE PREFIX'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 7fd8d054-c725-4e5b-a8ec-791900d01138
		summarizeBy: none
		sourceColumn: SERVICE PREFIX

		annotation SummarizationSetBy = Automatic

	/// The broad grouping of the service type (e.g. Career Services, Training, Support Services). Used to slice service counts by category in charts.
	column 'SERVICE CATEGORY'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 4b7f9a83-753f-4134-a718-5f19168c4fb3
		summarizeBy: none
		sourceColumn: SERVICE CATEGORY
		sortByColumn: 'CATEGORY SORT'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	/// Numeric sort order for service categories, ensuring they display in a logical sequence in charts and tables rather than alphabetically.
	column 'CATEGORY SORT'
		dataType: string
		displayFolder: TableColumns
		lineageTag: f7e8e8a6-89c7-4c22-ab31-115de6086eae
		summarizeBy: none
		sourceColumn: CATEGORY SORT

		annotation SummarizationSetBy = Automatic

	/// Numeric Local Workforce Development Board region code used to relate service records to the Regions table.
	column 'REGION CODE'
		dataType: string
		isHidden
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 7861f0a1-f99d-4c62-929a-ee8aded5ff11
		summarizeBy: none
		sourceColumn: REGION CODE

		annotation SummarizationSetBy = Automatic

	column 'SERVICE PROVIDED'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: adff7d82-c4d2-4077-bb02-46622cd0b815
		summarizeBy: none
		sourceColumn: SERVICE PROVIDED

		annotation SummarizationSetBy = Automatic

	partition ServicesProvided = m
		mode: import
		queryGroup: facts
		source = ```
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\StevenFoster\Downloads\Grant Enrollment Sample Data.xlsx"), true, true),
				  PromoteHeaders = Source{[Item = "Services", Kind = "Sheet"]}[Data],
				  TypePairs = {
				    {"CREATE DATE", type date}, 
				    {"ACTUAL BEGIN DATE", type date}, 
				    {"PROJECTED BEGIN DATE", type date}, 
				    {"ACTUAL END DATE", type date}, 
				    {"PROJECTED END DATE", type date}, 
				    {
				      "MOST RECENT EMPLOYMENT DATE", 
				      type date
				    }, 
				    {"USER ID", Int64.Type}, 
				    {"STATE ID", type text}, 
				    {"APP ID", type text}, 
				    {"REGION LWDB", type text}, 
				    {"OFFICE", type text}, 
				    {
				      "OFFICE OF RESPONSIBILITY", 
				      type text
				    }, 
				    {"SERVICE", type text}, 
				    {"NAICS", type text}, 
				    {"ONET", type text}, 
				    {"COMPLETION STATUS", type text}, 
				    {"PROGRAM", type text}, 
				    {"PROVIDER", type text}, 
				    {
				      "REGISTERED APPRENTICESHIP", 
				      type text
				    }, 
				    {
				      "TYPE OF APPRENTICESHIP", 
				      type text
				    }, 
				    {"HISPANIC", type text}, 
				    {"LEARNING MODE", type text}, 
				    {"AGENCY CODE", type text}, 
				    {"COMMENTS", type text}
				  }, 
				  ExistingCols = Table.ColumnNames(
				    PromoteHeaders
				  ), 
				  // Keep type rules only for columns that actually exist
				  TypePairsExistingOnly = List.Select(
				    TypePairs, 
				    each List.Contains(
				      ExistingCols, 
				      _{0}
				    )
				  ), 
				  // Convert those explicit pairs into a lookup record: ColumnName -> Type
				  ExplicitTypeMap = Record.FromList(
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{1}
				    ), 
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{0}
				    )
				  ), 
				  // - If we specified a type in ExplicitTypeMap, use it.
				  // - Otherwise default to type text.
				  AllTypePairs = List.Transform(
				    ExistingCols, 
				    (c) => {
				      c, 
				      Record.FieldOrDefault(
				        ExplicitTypeMap, 
				        c, 
				        type text
				      )
				    }
				  ), 
				  // Apply types in one go
				  ChangeTypes
				    = Table.TransformColumnTypes(
				    PromoteHeaders, 
				    AllTypePairs
				  )
				in
				  ChangeTypes
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

