/// The Enrollment Targets table defines planned enrollment goals by region, specifying the expected number of participants to be enrolled within each geographic area. It serves as a straightforward planning and accountability tool to track progress against regional enrollment expectations. Overall, the table supports monitoring, comparison, and alignment of enrollment efforts across regions.
table Targets
	lineageTag: 2c22dae7-5094-40fb-b55c-2947531131d6

	/// Planned enrollment target count for the site or region. Used as the target denominator in enrollment performance measures.
	column 'ENROLLMENT TARGETS'
		dataType: int64
		formatString: #,0
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: be5b1964-19fc-4f87-a55a-2a9b40526ef3
		summarizeBy: none
		sourceColumn: ENROLLMENT TARGETS

		annotation SummarizationSetBy = Automatic

	/// Source sub-code assigned to the enrollment target record. Used for site or source-level identification.
	column 'SUB CODE'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 517a7ebe-4c1a-4029-b879-78cb994fd000
		summarizeBy: none
		sourceColumn: SUB CODE

		annotation SummarizationSetBy = Automatic

	/// Site name associated with the enrollment target record.
	column SITE
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 39798ee8-b9d4-4706-8922-bdd67b0324aa
		summarizeBy: none
		sourceColumn: SITE

		annotation SummarizationSetBy = Automatic

	/// Local Workforce Development Board region name associated with the enrollment target.
	column 'REGION LWDB'
		dataType: string
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 59ed5379-9b96-4c5a-b9f2-fee8f234f973
		summarizeBy: none
		sourceColumn: REGION LWDB

		annotation SummarizationSetBy = Automatic

	/// Numeric Local Workforce Development Board region code used to relate targets to the Regions table.
	column 'REGION CODE'
		dataType: int64
		isHidden
		formatString: #,0
		isAvailableInMdx: false
		displayFolder: TableColumns
		lineageTag: 7b0fc800-58c6-4355-aab7-4d7b3c278f4e
		summarizeBy: none
		sourceColumn: REGION CODE

		annotation SummarizationSetBy = Automatic

	partition Targets = m
		mode: import
		queryGroup: facts
		source = ```
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\StevenFoster\Downloads\Grant Enrollment Sample Data.xlsx"), true, true),
				  PromoteHeaders = Source{[Item = "Targets", Kind = "Sheet"]}[Data]
				, 
				  TypePairs = {
				    {"ENROLLMENT TARGETS", Int64.Type}, 
				    {"SITE", type text}, 
				    {"REGION LWDB", type text}, 
				    {"SUB CODE", type text}, 
				    {"REGION CODE", Int64.Type}
				  }, 
				  ExistingCols = Table.ColumnNames(
				    PromoteHeaders
				  ), 
				  // Keep type rules only for columns that actually exist
				  TypePairsExistingOnly = List.Select(
				    TypePairs, 
				    each List.Contains(
				      ExistingCols, 
				      _{0}
				    )
				  ), 
				  // Convert those explicit pairs into a lookup record: ColumnName -> Type
				  ExplicitTypeMap = Record.FromList(
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{1}
				    ), 
				    List.Transform(
				      TypePairsExistingOnly, 
				      each _{0}
				    )
				  ), 
				  // - If we specified a type in ExplicitTypeMap, use it.
				  // - Otherwise default to type text.
				  AllTypePairs = List.Transform(
				    ExistingCols, 
				    (c) => {
				      c, 
				      Record.FieldOrDefault(
				        ExplicitTypeMap, 
				        c, 
				        type text
				      )
				    }
				  ), 
				  // Apply types in one go
				  ChangeTypes
				    = Table.TransformColumnTypes(
				    PromoteHeaders, 
				    AllTypePairs
				  )
				in 
				    ChangeTypes
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

