table Companies
	lineageTag: e1f7cfe1-71c4-46e1-af26-db9a003f8f05

	column 'Company Name'
		dataType: string
		displayFolder: TableColumns
		lineageTag: 1288e067-3155-41c8-b46a-4f6356f71398
		summarizeBy: none
		sourceColumn: Company Name

		annotation SummarizationSetBy = Automatic

	column 'Record ID #'
		dataType: int64
		formatString: 0
		lineageTag: 5cd0c320-45f5-4120-b6f6-e9cca7dd6a8e
		summarizeBy: none
		sourceColumn: Record ID #

		annotation SummarizationSetBy = Automatic

	partition Companies-c91aa4ea-dd1d-413b-ab1f-98f8247c9eb3 = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("C:\Users\Foster\Downloads\Termination-Report-Sample-Data.xlsx"), true, true),
				  _data = Source{[Item = "Companies", Kind = "Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(_data,{{"Record ID #", Int64.Type}})
				in
				  #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

