EVALUATE
	SELECTCOLUMNS(
		TOPN(
			100,
			'dimdate',
			'dimdate'[Date],
			ASC
		),
		'dimdate'[Date],
		'dimdate'[Calendar Year],
		'dimdate'[Month Name],
		'dimdate'[Month Number],
		'dimdate'[Weekday],
		'dimdate'[Weekday number],
		'dimdate'[Quarter],
		'dimdate'[Month Sort],
		'dimdate'[Month Year],
		'dimdate'[MonthOffset],
		'dimdate'[Quarter Number],
		'dimdate'[Quarter Year],
		'dimdate'[Quarter Start Date],
		'dimdate'[Quarter Sort],
		'dimdate'[QuarterOffset]
	)
	ORDER BY 'dimdate'[Date] DESC