
SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE 1 = 1 
AND COLUMN_NAME like '%dischargeReasonKey%' 
-- AND TABLE_NAME like '%FactPatientTask%'
order by TABLE_NAME


