SELECT 
		TABLE_CATALOG AS TableCatalog,
		TABLE_SCHEMA AS TableSchema,
		TABLE_NAME AS TableName,
		COLUMN_NAME AS ColumnName,
Case when DATA_TYPE IN ('varchar') Then Concat(Max(DATA_TYPE), '(', CHARACTER_MAXIMUM_LENGTH, ')') 
when DATA_TYPE IN ('nvarchar') Then Concat(Max(DATA_TYPE), '(', CHARACTER_MAXIMUM_LENGTH, ')')
	Else Max(DATA_TYPE) END as ColumnDataType
	,  ORDINAL_POSITION

FROM BSHHomeHealthCare_KinnserBI.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME LIKE '%FactM0Item%' 

GROUP BY TABLE_CATALOG , TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, ORDINAL_POSITION
Order by TableName,ORDINAL_POSITION

